### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by MilesQLi** [mwcvitkovic/Open-Vocabulary-Learning-on-Source-Code-with-a-Graph-Structured-Cache#2]
I tried to use "conda env create -f environment.yml" to create an environment but got the following problem:

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - pykerberos=1.1.14
  - graphite2=1.3.10
  - gstreamer=1.8.0
  - pango=1.40.3
  - gmp=6.1.2
  - libtool=2.4.6
  - harfbuzz=1.3.4
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libedit=3.1
  - jasper=1.900.1
  - readline=7.0
  - fontconfig=2.12.1
  - ncurses=6.0
  - glib=2.51.4
  - dbus=1.10.22
  - sparkmagic=0.12.5
  - libstdcxx-ng=7.2.0
  - gst-plugins-base=1.8.0
  - ptyprocess=0.5.2
  - x264=20131217
  - libgcc-ng=7.2.0 
```

I wonder how it is possible that there are conflicts since you successfully used an environment with the specification.

**Comment by mwcvitkovic** [comment]
Hi @MilesQLi, hard to know without more information, but there may be a conda version discrepancy.

Since there aren't too many dependencies, I'd recommend just manually installing the ones you need.   (`mxnet`, `sklearn`, `tqdm`, etc.)
