### ISSUE TITLE
Using model for method level tasks

### ISSUE THREAD

**Issue by hsellik** [mwcvitkovic/Open-Vocabulary-Learning-on-Source-Code-with-a-Graph-Structured-Cache#3]
Hi @mwcvitkovic ,

Thank you for a wonderful reproduction package!

I've been working on using models with vanilla AST-s generated with JavaParser for bug prediction task with some success. However, I believe your work (GGNN+GSC) opens up opportunities to improve. As you are the author of this source code, perhaps you can guide me a bit.

1) What would be required to use the approach as a binary classification model for method level tasks? 

(The aim is to have a supervised model and feed examples of good code and bad code in order to train. Later, use this trained model to get a prediction (bad/good) at a method level)

**Comment by mwcvitkovic** [comment]
Hey @hsellik, thanks for your interest!  I'm not quite sure what you're asking, however.  Can you make your question more specific?

As a general point, this paper is a few years old now.  You will almost certainly have more luck reimplementing the approach than trying to reuse our code.

**Comment by hsellik** [comment]
Hi @mwcvitkovic 

I think I found my answer.

So the idea is to have examples of Java methods which have a certain bug and then the same methods where the bug is fixed. Then train a machine learning model using these examples to detect the bugs. I used Code2Vec and Code2Seq models by Alon et al. for this with some success. They use vanilla AST-s and instead of graph networks, it is based on deterministic walks on the paths to turn nodes into a distributed representation. 

I saw a [talk by Yujia Li](https://youtu.be/_Uj-tNjhVDQ?t=390) saying that while these kinds of approaches are interesting, they are limited. I also saw the [presentation by Allamanis](https://www.youtube.com/watch?v=zCEYiCxrL_0) where he uses graph neural networks for prediction tasks so I figured I will give it a try. However, I am not too familiar with graph neural networks.

So the task is basically getting a distributed representation for a Java methods in order to use it for a downstream task of bug prediction. After reading a bit about GGNN-s, I see that while your paper looks at a specific node embedding, **I should combine all the node representations in a graph and then make predictions based on it.**

What I am planning to do is to use your augmented AST with a more powerful way of creating a distributed representation of a graph (GGNN) to see if it enhances the results. 

I hope this made more sense.

**Comment by mwcvitkovic** [comment]
Ah, the thing you're wondering about is called a "readout function" in the Graph NN world.  See [here](https://arxiv.org/pdf/1901.00596.pdf) for a recent GNN review that discusses them, or [here](https://arxiv.org/abs/1704.01212) for the paper that (I think) coined the term "readout function".

Training GNNs is tough, as is choosing the right readout function. **Definitely** read some recent papers on how to train GNNs.   They're not as finicky as GAN training used to be, but there's a lot of trickery involved.

But with some experimentation there's a reasonable chance you'll find a method that outperforms Code2Vec.

**Comment by hsellik** [comment]
Thank you for the answer!
